import createFetchClient from "openapi-fetch";
import createClient from "openapi-react-query";
import type { paths } from "@/lib/apiclient"; // generated by openapi-typescript
import { ACCESS_TOKEN_KEY } from "@/constants";

const fetchClient = createFetchClient<paths>({
  baseUrl: "https://myapi.dev/v1/",
  fetch: async (url, options = {}) => {
    const token = localStorage.getItem(ACCESS_TOKEN_KEY);

    const modifiedHeaders = new Headers({});
    if (token) {
      modifiedHeaders.set("Authorization", `Bearer ${token}`);
    }

    const modifiedOptions: RequestInit = {
      ...options,
      headers: modifiedHeaders,
      credentials: "include", // if your API needs cookies/session
    };

    try {
      const response = await fetch(url, modifiedOptions);

      // Intercept 401 errors and handle token removal
      if (response.status === 401) {
        localStorage.removeItem(ACCESS_TOKEN_KEY);
      }

      return response;
    } catch (err) {
      console.error("Request failed", err);
      throw err;
    }
  },
});

export const $api = createClient(fetchClient);
